CREATE TABLE IF NOT EXISTS tasks (
	id INT(11) PRIMARY KEY NOT NULL,
	title VARCHAR(20) NOT NULL,
	description VARCHAR(250) NULL,
	state INT(1) NOT NULL DEFAULT 0,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NULL,
	task_lists_id INT(11)
);

CREATE TABLE IF NOT EXISTS task_lists (
    id INT(11) PRIMARY KEY NOT NULL,
	title VARCHAR(20) NOT NULL,
	description VARCHAR(250) NULL,
)